name: Build

on:
  pull_request:
    branches:
      - master
    types: [synchronize]

  push:
    branches:
      - "**"
      - "!master"

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint